version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Test
          command: npm run ci
