// Generated by CoffeeScript 1.12.7
(function() {
  var EventEmitter, MiddlewareHandler, Promise, basicAuthParser, connectSocket, http, net, url;

  http = require('http');

  net = require('net');

  url = require('url');

  Promise = require('bluebird');

  basicAuthParser = require('basic-auth-parser');

  EventEmitter = require('events').EventEmitter;

  MiddlewareHandler = require('middleware-handler');

  MiddlewareHandler.prototype = Promise.promisifyAll(MiddlewareHandler.prototype);

  connectSocket = function(arg) {
    var cltSocket, connect, head, hostname, port, req;
    cltSocket = arg.cltSocket, hostname = arg.hostname, port = arg.port, head = arg.head, connect = arg.connect, req = arg.req;
    return connect(port, hostname, cltSocket, req).then(function(srvSocket) {
      cltSocket.write('HTTP/1.0 200 Connection Established\r\nProxy-agent: Resin-VPN\r\n\r\n');
      srvSocket.write(head);
      srvSocket.pipe(cltSocket, {
        end: false
      });
      cltSocket.pipe(srvSocket, {
        end: false
      });
      return Promise.fromNode(function(cb) {
        cltSocket.on('error', cb);
        srvSocket.on('error', cb);
        cltSocket.on('end', cb);
        return srvSocket.on('end', cb);
      })["finally"](function() {
        srvSocket.destroy();
        return cltSocket.destroy();
      });
    })["catch"](function(e) {
      cltSocket.end('HTTP/1.0 500 Internal Server Error\r\n');
      cltSocket.destroy();
      throw e;
    });
  };

  exports.createTunnel = function() {
    var middleware, server, tunnel;
    tunnel = new EventEmitter();
    middleware = new MiddlewareHandler();
    server = http.createServer(function(req, res) {
      res.writeHead(405, {
        'Content-Type': 'text/plain'
      });
      return res.end('Method not allowed');
    });
    server.on('connect', function(req, cltSocket, head) {
      return middleware.handleAsync([req, cltSocket, head]).then(function() {
        var srvUrl;
        srvUrl = url.parse("http://" + req.url);
        return connectSocket({
          cltSocket: cltSocket,
          hostname: srvUrl.hostname,
          port: srvUrl.port,
          head: head,
          connect: tunnel.connect,
          req: req
        }).then(function() {
          return tunnel.emit('connect', srvUrl.hostname, srvUrl.port, head);
        });
      })["catch"](function(err) {
        tunnel.emit('error', err);
        return cltSocket.destroy();
      });
    });
    tunnel.connect = Promise.method(net.connect);
    tunnel.use = middleware.use.bind(middleware);
    tunnel.listen = server.listen.bind(server);
    tunnel.close = server.close.bind(server);
    return tunnel;
  };

  exports.basicAuth = function(req, cltSocket, head, next) {
    if (req.headers['proxy-authorization'] != null) {
      req.auth = basicAuthParser(req.headers['proxy-authorization']);
    }
    return next();
  };

}).call(this);
